Fixed a swift compilation error
Fixed the following error:
QRScanner.swift:484:74: 'openSettingsURLString' has been renamed to 'UIApplicationOpenSettingsURLString'